### ISSUE TITLE
Get a visible site title

### ISSUE THREAD

**Issue by joede** [seanlane/gochowdown#1]
This is my first contact with Hugo and with this theme. I've tried to get the configured title of the site (`{{ .Site.title}}`) into the navigation bar.

I've done this by adding an entry into `<nav>` section of `header.html`. Here I used `<h1>` to get a bigger this.

In the end, the result looks ugly (wrong font, wrong color, bad spacing). I don't know which CSS styles I have to use to get a proper look and feel. ;-)

Could you please add the title into the navigation bar area?
Could this be "switchable" from within `config.yml`?

**Comment by seanlane** [comment]
Sounds good to me, shouldn't take too long to throw something together.

**Comment by seanlane** [comment]
In `config.yml` under `params`, set the key `showNavTitle` to a value of `true` to show the title, or `false` or delete the key to hide the title, hence it's hidden by default.

Example: https://github.com/seanlane/gochowdown/blob/3bdeb9968435eafb4897072a2ce1a88a3b8d6eb2/exampleSite/config.yml#L25

**Comment by joede** [comment]
Great! Thank you for the fast result. I've seen you have updated your own site with a title too? Exactly the way it should be. ;-) 

Normally I'm using Pelican which is part of my (preferred) Debian Linux. This was the first time I've tried Hugo. Very interesting....

By the way... I had to use *Hugo extended* to get your theme up and running. If this is ok, you should add a note to the readme.

**Comment by seanlane** [comment]
Yep, it wasn't something I noticed as being missing until you mentioned it.

Thanks for mentioning that, I actually didn't realize there was an extended version of Hugo (my inexperience with Hugo is showing here 😄). I've been using either Homebrew or the Arch User Repository to install, seems like both of them use Hugo extended. From what I can tell, the only difference is that Hugo extended comes with support for SASS/SCSS processing?

If that's the case, then yes it's required because the theme uses SCSS. I'll make a note of that on the README

**Comment by seanlane** [comment]
Note for others in the future:

* Apparently there is more to the extended version than just SASS/SCSS (https://discourse.gohugo.io/t/should-i-use-hugo-extended-for-a-new-hugo-project/13954/3)
* It also allegedly should work without Hugo extended by committing the `resources` directory from the theme according to (https://discourse.gohugo.io/t/should-i-use-hugo-extended-for-a-new-hugo-project/13954/3) but I was able to reproduce the error. I don't have time to figure out the cause of the issue, so just going to leave Hugo extended as a requirement for now.
