### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Sawrz** [seanlane/gochowdown#20]
Hi,
Thank you for your great work with GoChowdown. I think Hugo needs more recipe themes like that (or at all)!

However, there are some things I would like to change, like the navbar, recipe listings, etc. So, it becomes more or less its own thing. So I thought about giving it its own name like GoChopChop (I'm open for input). In the end, that would mean more variety what is beneficial for everybody involved.

Instead of starting at zero, and because I like GoChowdown, I decided to fork your project and edit it to my liking. However, to value your and the communities work, I'm not sure how to treat the licensing. As far as I know, I need to stick with the same license type, which is MIT (I'm fine with that). 
There still is the copyright note within the license with your name, @seanlane. My idea is to add another line below your name and add mine, so you keep the copyright of the code you contributed. In addition to that, I would like to add in the README that my project is a fork of GoChowdown with a link to this project. 

Are you ok with that? I know according to the license, I can redistribute, etc., but I think it's only fair to ask you if you agree with how I want to handle the license stuff.  =)

**Comment by seanlane** [comment]
Hi there, I'm glad you've found this theme useful! It was originally inspired by https://github.com/clarklab/chowdown and it's certainly open for anyone to fork and modify as they see fit.

> I'm not sure how to treat the licensing. As far as I know, I need to stick with the same license type, which is MIT (I'm fine with that).

When I did my original fork, I believe there wasn't a licence, though the original project now seems to be licensed by the Unlicense license. I added the MIT license at the time since it seemed common and fairly free, only requiring other works to be similarly free.

> There still is the copyright note within the license with your name, @seanlane. My idea is to add another line below your name and add mine, so you keep the copyright of the code you contributed. 

According to this, that seems correct to me: https://softwareengineering.stackexchange.com/a/277699

> In addition to that, I would like to add in the README that my project is a fork of GoChowdown with a link to this project.

That's not required, but is certainly appreciated :)

> Are you ok with that? I know according to the license, I can redistribute, etc., but I think it's only fair to ask you if you agree with how I want to handle the license stuff. =)

I appreciate the courtesy, and everything you've proposed seems more than fine to me. I agree with you, there's certainly a lack of recipe themes for Hugo, and I think more effort in the area can only be a positive thing. I'll leave this open for now in case there's any further questions I can help with, and I look forward to seeing your work 😃

**Comment by seanlane** [comment]
No further questions, going to close this now.

**Comment by Sawrz** [comment]
Indeed =)

I finished my fork on Gitlab (although I have a mirror on GitHub yet): https://gitlab.com/sawrz/gourmet-secrets

If you have time and motivation, you might want to check the README (or the theme) and give me your opinion on it. I would appreciate that =)
