### ISSUE TITLE
Yield, cooking and preparation times are not used?

### ISSUE THREAD

**Issue by andrewshadura** [seanlane/gochowdown#3]
Hi,

I tried to publish some of the recipes using GoChowDown and noticed none of yield, cooking or preparation times end up anywhere in the output. I haven’t checked, but probably there’s more of those.

I may at some point send a pull request, but please consider adding these.

**Comment by seanlane** [comment]
Yeah, that's correct, the fields aren't used. I have them there for an eventual update that could use them, but I haven't had time to update this much due to other commitments. Any pull request adding these or other features would be more than welcome, and if I do get time I'll look into adding them as well myself.

**Comment by seanlane** [comment]
Closed with #4

**Comment by yegle** [comment]
Looks like {author,source}{Name,URL} are also not included in the generated file?

**Comment by seanlane** [comment]
@yegle yes, at the moment, they are not currently being used. I intent to incorporate them eventually, when time allows.
